on:
    pull_request:
      branches:
        - main
        # - master
    push:
      branches:
        - main
        # - master    
name: "Build & Release"
jobs:
    build:
      name: Build & Release
      runs-on: ubuntu-latest # You can also switch to 'ubuntu-latest' if you're focusing only on Android
  
      steps:
        - uses: actions/checkout@v1
  
        - uses: actions/setup-java@v1
          with:
            java-version: '17.0.12'
  
        - uses: subosito/flutter-action@v1
          with:
            flutter-version: '3.24.3'
  
        - run: flutter pub get
  
        
  
        # Build Android APK in debug mode, you can change to `--release` for a release version
        - run: flutter build apk --debug
  
        # Only keep Android artifact steps
        - name: Push to Releases
          uses: actions/upload-artifact@v1
          with:
            path: "build/app/outputs/"  # Android APK output path for release builds
            name: dubug-apk

          
  